selection_foreground    #F7F2E4
selection_background    #CFC5A4

background              #2B2B2B
foreground              #F7F2E4

color0                  #505050
color1                  #CE908C
color2                  #B6B9A3
color3                  #CFC5A4
color4                  #D0C6A6
color5                  #CEC9AA
color6                  #E8DAB1
color7                  #EBE4D0
color8                  #A4A091
color9                  #CE908C
color10                 #B6B9A3
color11                 #CFC5A4
color12                 #D0C6A6
color13                 #CEC9AA
color14                 #E8DAB1
color15                 #EBE4D0

cursor                  #F7F2E4
cursor_text_color       #2B2B2B

url_color               #D0C6A6

active_tab_foreground   #2B2B2B
active_tab_background   #D0C6A6
inactive_tab_foreground #F7F2E4
inactive_tab_background #505050
